/// Token art, generated rather than uploaded. OpenRouter in front of an image model, so the key is
/// one the caller already has. Returns bytes; where they get pinned is the caller's business.
export interface GenerateImageOptions {
  prompt: string;
  apiKey?: string;
  model?: string;
  /// A short style line appended to the prompt. Defaults to what a token avatar has to be: legible
  /// at 32 pixels, one subject, flat, no text.
  style?: string;
  referer?: string;
}

const DEFAULT_STYLE =
  "token avatar, one subject centred, flat bold shapes, high contrast, readable at 32 pixels, " +
  "no text, no watermark, square";

export interface GeneratedImage {
  bytes: Uint8Array;
  mimeType: string;
  dataUri: string;
  model: string;
}

export async function generateImage(opts: GenerateImageOptions): Promise<GeneratedImage> {
  const apiKey = opts.apiKey ?? process.env.OPENROUTER_API_KEY;
  if (!apiKey) throw new Error("no OPENROUTER_API_KEY: set it, or pass apiKey");
  const model = opts.model ?? process.env.HOOD_IMAGE_MODEL ?? "google/gemini-2.5-flash-image";

  const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: {
      authorization: `Bearer ${apiKey}`,
      "content-type": "application/json",
      "http-referer": opts.referer ?? "https://hood.fam",
      "x-title": "hood.fam",
    },
    body: JSON.stringify({
      model,
      modalities: ["image", "text"],
      messages: [{ role: "user", content: `${opts.prompt}. ${opts.style ?? DEFAULT_STYLE}` }],
    }),
  });

  if (!res.ok) throw new Error(`image generation failed: ${res.status} ${await res.text()}`);
  const json = (await res.json()) as {
    choices?: { message?: { images?: { image_url?: { url?: string } }[] } }[];
  };
  const url = json.choices?.[0]?.message?.images?.[0]?.image_url?.url;
  if (!url?.startsWith("data:")) throw new Error("the model returned no image");

  const [header, base64] = url.split(",", 2);
  const mimeType = header!.slice(5).split(";")[0] ?? "image/png";
  return { bytes: Buffer.from(base64!, "base64"), mimeType, dataUri: url, model };
}

/// Where generated bytes go so a launch carries a link. The API addresses the object by its own
/// hash, so uploading the same image twice is one object and the second answer says so.
export interface UploadImageOptions {
  /// The indexer API's base, the same one the app talks to. No trailing slash needed.
  apiUrl: string;
  bytes: Uint8Array;
  contentType?: string;
}

export interface UploadedImage {
  url: string;
  key: string;
  bytes: number;
  contentType: string;
  deduped: boolean;
}

/// Carries the status so a caller can tell "this deployment has no bucket" (501) from "that image
/// is too big" (413) and say something useful instead of retrying.
export class ImageUploadError extends Error {
  constructor(readonly status: number, message: string) {
    super(message);
    this.name = "ImageUploadError";
  }
}

/// A plain POST to /uploads/image. Optional by design: storage may be off, and every caller has a
/// path that still works when it is.
export async function uploadImage(opts: UploadImageOptions): Promise<UploadedImage> {
  const base = opts.apiUrl.replace(/\/+$/, "");
  const contentType = opts.contentType ?? "image/png";
  const base64 = Buffer.from(opts.bytes).toString("base64");
  const res = await fetch(`${base}/uploads/image`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ dataUri: `data:${contentType};base64,${base64}` }),
  });
  const json = (await res.json().catch(() => null)) as (UploadedImage & { error?: string }) | null;
  if (!res.ok || !json?.url) {
    throw new ImageUploadError(res.status, json?.error ?? `upload failed: ${res.status}`);
  }
  return json;
}
