// Generates packages/sdk/src/abi.generated.ts from the Foundry artifacts.
// Run after `forge build`, so the SDK can never drift from the deployed bytecode.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const wanted = [
  "HoodFactory",
  "HoodCurve",
  "HoodCurveRouter",
  "HoodToken",
  "HoodFeeRouter",
  "HoodStaking",
  "HoodTokenLock",
  "UniswapV4Graduator",
  "HoodBridgeFactory",
  "HoodOFTAdapter",
  "HoodPortal",
  "HoodDirectDeployer",
  "HoodLaunchToken",
  "HoodLaunchHook",
  "HoodRevenueSplitter",
  "HoodLocker",
  "HoodBuybackModule",
  "HoodSeasonDrop",
];

const out = [
  "// Generated by scripts/abis.mjs from the Foundry artifacts. Do not edit by hand.",
  "",
];
for (const name of wanted) {
  const path = resolve(root, "out", `${name}.sol`, `${name}.json`);
  if (!existsSync(path)) throw new Error(`missing artifact: ${path} (run forge build)`);
  const artifact = JSON.parse(readFileSync(path, "utf8"));
  out.push(`export const ${name.charAt(0).toLowerCase()}${name.slice(1)}Abi = ${JSON.stringify(artifact.abi)} as const;`);
  out.push("");
}
const target = resolve(root, "packages/sdk/src/abi.generated.ts");
const generated = out.join("\n");

// `--check` compares instead of writing, for a place where drift is silent and expensive: a
// function added to a contract and never regenerated here simply does not exist as far as the SDK,
// the app and every harness are concerned. That is how HoodCurve.claimProtocol stayed invisible
// after it was written.
if (process.argv.includes("--check")) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (current !== generated) {
    console.error(`${target} is out of date with the artifacts in out/. Run: npm run abis`);
    process.exit(1);
  }
  console.log(`abis are up to date (${wanted.length})`);
} else {
  writeFileSync(target, generated);
  console.log(`wrote ${target} (${wanted.length} abis)`);
}
